version: '3'
services:

    mongo:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - "${DATA_LOCATION}/mongo:/data/db"

    redis:
        image: redis:latest
        restart: unless-stopped

    xapi:
        image: learninglocker/xapi-service:${XAPI_SERVICE_VERSION}
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - MONGO_DB=learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/xapi-storage:/usr/src/app/storage"

    api:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    ui:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
            - api
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
            - "${DATA_LOCATION}/ui-logs:/opt/learninglocker/logs"

    worker:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    nginx:
        image: learninglocker-nginx:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
        restart: unless-stopped
        depends_on:
            - ui
            - xapi
        ports:
            - "443:443"
            - "8080:80"